config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :items
  get 'main/login'
  get 'main/user_item'
  post 'main/login'
  post 'main/create'
  delete 'items/:id', to: 'items#destroy', as: 'delete_item'
  get 'items/new/:id', to: 'items#new_user_item', as: 'new_user_item'
  get 'shop/:id', to: 'main#shop'
  post 'main/buy/:id/:user_id', to: 'main#buy', as: "main_buy" 
  get 'main/inventories'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # before_action :must_be_logged_in 
  
  def login
  end

  def create 
    user = User.where(login: params[:login]).first
    if user && user.authenticate(params[:password])
      redirect_to main_user_item_path
      session[:logged_in] = true
      session[:userId] = user.id
    else
      redirect_to main_login_path, alert: 'wrong username or password'
    end
  end

  def user_item 
    if must_be_logged_in
      @user = User.where(id: session[:userId]).first
      @user_items = Item.where(user_id: session[:userId])
      @order = 1
    end
  end

  def shop
    if must_be_logged_in
      @user_id = params[:id]
      @user_items = Item.where(user_id: params[:id])    
      @order = 1
    end
  end

  def buy
    if must_be_logged_in
      item = Item.where(id: params[:id])
      if item[0]["stock"].to_i > 0  
        item_left = item[0]["stock"].to_i - 1
        Inventory.create(price: item[0]["price"], user_id: session[:userId], item_id: params[:id])
        item.update(stock: item_left)
        redirect_to :action => "shop", :id => params[:user_id]
      else 
        redirect_to :action => "shop", alert: "This item is out of order", :id => params[:user_id]
      end
    end
  end

  def inventories
    if must_be_logged_in
      @data = []
      @order = 1
      my_items = Inventory.where(user_id: session[:userId])
      my_items.each do |item| 
        item_info = Item.where(id: item.item_id)
        user = User.where(id: item_info[0]["user_id"])
        @data.push([user[0]["login"], item_info[0]["name"], my_items[0]["price"], my_items[0]["created_at"]])
      end
      pp @data
    end
  end

  def destroy
    reset_session
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/inventories.html.erb
<div class="container mt-4 mb-4">
    <h1>Inventories</h1>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Order</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Dealer</th>
            <th scope="col">Time</th>
        </tr>
    </thead>
    <tbody>
        <% @data.each do |h| %>
            <tr>
                <th scope="row"><%= @order %></th>
                <td><%= h[1] %></td>
                <td><%= h[2] %></td>
                <td><%= h[0] %></td>
                <td><%= h[3] %></td>
            </tr>
            <% @order += 1 %>
        <% end %>
    </tbody>
    </table>
</div>

app/views/main/login.html.erb
<h1>Login</h1>
<%= form_with url: main_create_path, method: :post, data: {turbo: false} do |form| %>
    <div class="mb-3">
        <label for="login" class="form-label">Username</label>
        <input type="text" name="login" class="form-control" aria-describedby="loginHelp">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" name="password" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
<% end %>    

app/views/main/shop.html.erb
<div class="container mt-4 mb-4">
    <h1>Shop</h1>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Order</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <% @user_items.each do |item| %>
            <tr>
                <th scope="row"><%= @order %></th>
                <td><%= item.name %></td>
                <td><%= item.price %></td>
                <td><%= item.stock %></td>
                <td class="d-flex">
                    <% if item.stock > 0%>
                        <%= button_to "Buy", main_buy_path(item.id, @user_id), class: 'btn btn-primary' %> &nbsp;&nbsp;&nbsp;
                    <% else %>
                        <p>out of order</p>
                    <% end %>
                </td>
            </tr>
            <% @order += 1 %>
        <% end %>
    </tbody>
    </table>
</div>

app/views/main/user_item.html.erb
<div class="container mt-4 mb-4">
    <h1>Item</h1>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Order</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <% @user_items.each do |item| %>
            <tr>
                <th scope="row"><%= @order %></th>
                <td><%= item.name %></td>
                <td><%= item.price %></td>
                <td><%= item.stock %></td>
                <td class="d-flex">
                    <%= button_to "Edit", edit_item_path(item.id), method: :get, class: 'btn btn-secondary' %>&nbsp;&nbsp;&nbsp;
                    <%= button_to "Delete", delete_item_path(item.id) , method: :delete, class: 'btn btn-danger' %> 
                </td>
            </tr>
            <% @order += 1 %>
        <% end %>
    </tbody>
    </table>
    <%= link_to "New item", new_user_item_path(@user.id), class: 'btn btn-success' %>
</div>