config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :items
  get 'main/login'
  get 'main/user_item'
  post 'main/login'
  post 'main/create'
  delete 'items/:id', to: 'items#destroy', as: 'delete_item'
  get 'items/new/:id', to: 'items#new_user_item', as: 'new_user_item'
  get 'shop/:id', to: 'main#shop'
  post 'main/buy/:id/:user_id', to: 'main#buy', as: "main_buy" 
  get 'main/inventories'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:user_id, :item_id, :price, :user_id, :item_id)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>User:</strong>
    <%= inventory.user_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= inventory.item_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= inventory.price %>
  </p>

  <p>
    <strong>User:</strong>
    <%= inventory.user_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= inventory.item_id %>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventories</h1>

<div id="inventories">
  <% @inventories.each do |inventory| %>
    <%= render inventory %>
    <p>
      <%= link_to "Show this inventory", inventory %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory", new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Edit this inventory", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to inventories", inventories_path %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete %>
</div>