config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :items
  get 'main/login'
  get 'main/user_item'
  post 'main/login'
  post 'main/create'
  delete 'items/:id', to: 'items#destroy', as: 'delete_item'
  get 'items/new/:id', to: 'items#new_user_item', as: 'new_user_item'
  get 'shop/:id', to: 'main#shop'
  post 'main/buy/:id/:user_id', to: 'main#buy', as: "main_buy" 
  get 'main/inventories'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  def new_user_item
    @item = Item.new
    @user_id = params[:id]
    render "new2"
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:user_id, :price, :name, :stock, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_form2.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <%= hidden_field_tag("item[user_id]", @user_id) %>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>User:</strong>
    <%= item.user_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= item.stock %>
  </p>

  <p>
    <strong>User:</strong>
    <%= item.user_id %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item, class: 'btn btn-primary' %>
  <%= link_to "Back to items", items_path, class: 'btn btn-secondary' %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/new2.html.erb
<h1>New item</h1>

<%= render "form2", item: @item %>

<br>

<div>
  <%= link_to "Back to items", main_user_item_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>